import React from "react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import {
  FiBookOpen,
  FiDatabase,
  FiTarget,
  FiShare2,
  FiMail,
  FiClock,
  FiShield,
  FiUserCheck,
  FiSliders,
  FiActivity,
  FiUserX,
  FiEdit,
  FiLock,
  FiPhoneCall
} from "react-icons/fi";

export default function PrivacyPage() {
  return (
    <div className="min-h-screen flex flex-col bg-brand-bg">
      <Header />
      <main className="flex-grow py-16">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 space-y-8">
          <div className="text-center space-y-4">
            <h1 className="font-serif text-4xl sm:text-5xl font-bold text-brand-navy">
              Privacy Policy
            </h1>
            <p className="text-sm sm:text-base text-brand-slate max-w-xl mx-auto">
              Your privacy is extremely important to us. Learn how we collect, store, and protect your personal information.
            </p>
            <p className="text-xs text-brand-slate/60">Last updated: August 29, 2026</p>
          </div>

          <div className="bg-white border border-brand-border/60 rounded-3xl p-8 sm:p-12 shadow-sm space-y-10 text-brand-slate text-sm sm:text-base leading-relaxed">
            
            {/* Introduction */}
            <section className="space-y-4">
              <p>
                <strong>Niela</strong> (&ldquo;we,&rdquo; &ldquo;our,&rdquo; or &ldquo;us&rdquo;) is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed when you use our website and services.
              </p>
              <p>
                This Privacy Policy applies to our website and its associated subdomains (collectively, our &ldquo;Service&rdquo;). By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Use.
              </p>
            </section>

            {/* Definitions */}
            <section className="space-y-4">
              <h2 className="font-serif text-xl sm:text-2xl font-bold text-brand-navy border-b border-brand-border/40 pb-3 flex items-center gap-3">
                <FiBookOpen className="w-5 h-5 text-brand-pink shrink-0" />
                Definitions and Key Terms
              </h2>
              <p className="text-xs sm:text-sm text-brand-slate/80 mb-4">
                To help explain things as clearly as possible, whenever these terms are used in this Privacy Policy, they carry the following meaning:
              </p>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="p-4 bg-brand-bg/50 border border-brand-border/40 rounded-2xl">
                  <span className="font-semibold text-brand-navy block text-sm mb-1">Cookie</span>
                  <span className="text-xs text-brand-slate">A small amount of data generated by a website and saved by your web browser, used to identify your browser, provide analytics, or remember your preferences.</span>
                </div>
                <div className="p-4 bg-brand-bg/50 border border-brand-border/40 rounded-2xl">
                  <span className="font-semibold text-brand-navy block text-sm mb-1">Company</span>
                  <span className="text-xs text-brand-slate">When this policy refers to &ldquo;Company,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our,&rdquo; it means Poiya Healthcare India Private Limited, the entity responsible for your info.</span>
                </div>
                <div className="p-4 bg-brand-bg/50 border border-brand-border/40 rounded-2xl">
                  <span className="font-semibold text-brand-navy block text-sm mb-1">Country</span>
                  <span className="text-xs text-brand-slate">Where Niela and its owners are based, in this case, India.</span>
                </div>
                <div className="p-4 bg-brand-bg/50 border border-brand-border/40 rounded-2xl">
                  <span className="font-semibold text-brand-navy block text-sm mb-1">Device</span>
                  <span className="text-xs text-brand-slate">Any internet-connected device &mdash; such as a phone, tablet, or computer &mdash; used to visit Niela and use our services.</span>
                </div>
                <div className="p-4 bg-brand-bg/50 border border-brand-border/40 rounded-2xl">
                  <span className="font-semibold text-brand-navy block text-sm mb-1">IP Address</span>
                  <span className="text-xs text-brand-slate">A number assigned to every internet device, often used to estimate the general location from which a device is connecting.</span>
                </div>
                <div className="p-4 bg-brand-bg/50 border border-brand-border/40 rounded-2xl">
                  <span className="font-semibold text-brand-navy block text-sm mb-1">Personal Data</span>
                  <span className="text-xs text-brand-slate">Any information that directly or indirectly allows for the identification of a natural person.</span>
                </div>
                <div className="p-4 bg-brand-bg/50 border border-brand-border/40 rounded-2xl">
                  <span className="font-semibold text-brand-navy block text-sm mb-1">Service</span>
                  <span className="text-xs text-brand-slate">Refers to the period care and feminine hygiene service provided by Niela as described on this website.</span>
                </div>
                <div className="p-4 bg-brand-bg/50 border border-brand-border/40 rounded-2xl">
                  <span className="font-semibold text-brand-navy block text-sm mb-1">Third-Party Service</span>
                  <span className="text-xs text-brand-slate">Refers to advertisers, promotional/marketing partners, and others who provide content or services we think may interest you.</span>
                </div>
              </div>
            </section>

            {/* Information Collected */}
            <section className="space-y-4">
              <h2 className="font-serif text-xl sm:text-2xl font-bold text-brand-navy border-b border-brand-border/40 pb-3 flex items-center gap-3">
                <FiDatabase className="w-5 h-5 text-brand-pink shrink-0" />
                What Information Do We Collect?
              </h2>
              <p>
                We collect information from you when you visit our website, register on our site, place an order, subscribe to our newsletter, or fill out a form. This may include:
              </p>
              <ul className="list-disc pl-5 space-y-1">
                <li>Name / Username</li>
                <li>Phone Numbers</li>
                <li>Email Addresses</li>
                <li>Mailing/Delivery Addresses</li>
              </ul>
            </section>

            {/* How we use the information */}
            <section className="space-y-4">
              <h2 className="font-serif text-xl sm:text-2xl font-bold text-brand-navy border-b border-brand-border/40 pb-3 flex items-center gap-3">
                <FiTarget className="w-5 h-5 text-brand-pink shrink-0" />
                How Do We Use The Information We Collect?
              </h2>
              <p>
                Any information we collect from you may be used to:
              </p>
              <ul className="list-disc pl-5 space-y-1">
                <li>Personalize your experience on our website</li>
                <li>Improve our website based on your feedback</li>
                <li>Improve customer service and support</li>
                <li>Process transactions and orders safely</li>
                <li>Administer a contest, promotion, survey, or other site feature</li>
                <li>Send periodic emails and order tracking updates</li>
              </ul>
            </section>

            {/* Sharing information */}
            <section className="space-y-4">
              <h2 className="font-serif text-xl sm:text-2xl font-bold text-brand-navy border-b border-brand-border/40 pb-3 flex items-center gap-3">
                <FiShare2 className="w-5 h-5 text-brand-pink shrink-0" />
                Do We Share Information With Third Parties?
              </h2>
              <p>
                We may share the personal and non-personal information we collect with trusted third-party service providers who help us operate our business &mdash; such as website hosting, database management, email delivery, payment processing (including our gateway partner <strong>Razorpay</strong>), and order fulfillment. These parties are only given the information they need to perform their services for us and are required to keep it confidential.
              </p>
              <p>
                We may also disclose personal information to government or law enforcement authorities where we believe in good faith that disclosure is necessary to comply with a legal obligation, protect our rights, or ensure the safety of our users.
              </p>
            </section>

            {/* Email Address Usage */}
            <section className="space-y-4">
              <h2 className="font-serif text-xl sm:text-2xl font-bold text-brand-navy border-b border-brand-border/40 pb-3 flex items-center gap-3">
                <FiMail className="w-5 h-5 text-brand-pink shrink-0" />
                How Do We Use Your Email Address?
              </h2>
              <p>
                By submitting your email address on this website, you agree to receive emails from us regarding your orders, offers, and updates. You can unsubscribe at any time using the opt-out link included in any email we send. We do not send unsolicited commercial emails.
              </p>
            </section>

            {/* Retention */}
            <section className="space-y-4">
              <h2 className="font-serif text-xl sm:text-2xl font-bold text-brand-navy border-b border-brand-border/40 pb-3 flex items-center gap-3">
                <FiClock className="w-5 h-5 text-brand-pink shrink-0" />
                How Long Do We Keep Your Information?
              </h2>
              <p>
                We retain your information only for as long as necessary to provide our Service and fulfill the purposes described in this policy, or as required to meet our legal obligations. When it is no longer needed, we remove it from our systems or anonymize it.
              </p>
            </section>

            {/* Protection */}
            <section className="space-y-4">
              <h2 className="font-serif text-xl sm:text-2xl font-bold text-brand-navy border-b border-brand-border/40 pb-3 flex items-center gap-3">
                <FiShield className="w-5 h-5 text-brand-pink shrink-0" />
                How Do We Protect Your Information?
              </h2>
              <p>
                We implement a variety of security measures to protect your personal information. All sensitive or payment information is transmitted via Secure Socket Layer (SSL) technology and processed through our secure payment gateway partner. Your payment details are never stored on our servers after a transaction is complete. While we take reasonable steps to protect your information, no method of transmission or storage is 100% secure, and we cannot guarantee absolute security.
              </p>
            </section>

            {/* Account updates */}
            <section className="space-y-4">
              <h2 className="font-serif text-xl sm:text-2xl font-bold text-brand-navy border-b border-brand-border/40 pb-3 flex items-center gap-3">
                <FiUserCheck className="w-5 h-5 text-brand-pink shrink-0" />
                Can I Update or Correct My Information?
              </h2>
              <p>
                You can contact us at any time to update or correct your personal information, change your communication preferences, or request deletion of your account and associated data. We may take reasonable steps, such as verifying your identity, before making these changes.
              </p>
            </section>

            {/* Cookies */}
            <section className="space-y-4">
              <h2 className="font-serif text-xl sm:text-2xl font-bold text-brand-navy border-b border-brand-border/40 pb-3 flex items-center gap-3">
                <FiSliders className="w-5 h-5 text-brand-pink shrink-0" />
                Cookies
              </h2>
              <p>
                Niela uses cookies to identify the areas of our website you have visited and to enhance site performance and functionality. Cookies are non-essential, but disabling them may limit certain features, such as staying logged in between visits. You can disable cookies through your browser settings at any time.
              </p>
            </section>

            {/* Remarketing */}
            <section className="space-y-4">
              <h2 className="font-serif text-xl sm:text-2xl font-bold text-brand-navy border-b border-brand-border/40 pb-3 flex items-center gap-3">
                <FiActivity className="w-5 h-5 text-brand-pink shrink-0" />
                Advertising and Remarketing
              </h2>
              <p>
                Our website may use remarketing and interest-based advertising services, such as the Facebook Pixel, to show you more relevant ads based on your browsing activity on our site. We are not responsible for the content or privacy practices of third-party advertisers or websites linked from our Service.
              </p>
            </section>

            {/* Children's Privacy */}
            <section className="space-y-4">
              <h2 className="font-serif text-xl sm:text-2xl font-bold text-brand-navy border-b border-brand-border/40 pb-3 flex items-center gap-3">
                <FiUserX className="w-5 h-5 text-brand-pink shrink-0" />
                Children&apos;s Privacy
              </h2>
              <p>
                Our Service is not directed at children, and we do not knowingly collect personal information from children under the age of 13. If you are a parent or guardian and believe your child has provided us with personal data without your consent, please contact us so we can remove it.
              </p>
            </section>

            {/* Changes */}
            <section className="space-y-4">
              <h2 className="font-serif text-xl sm:text-2xl font-bold text-brand-navy border-b border-brand-border/40 pb-3 flex items-center gap-3">
                <FiEdit className="w-5 h-5 text-brand-pink shrink-0" />
                Changes To This Privacy Policy
              </h2>
              <p>
                We may update this Privacy Policy from time to time to reflect changes to our Service or legal requirements. We will notify you of significant changes through our website. Continued use of our Service after changes take effect means you accept the updated policy.
              </p>
            </section>

            {/* Law */}
            <section className="space-y-4">
              <h2 className="font-serif text-xl sm:text-2xl font-bold text-brand-navy border-b border-brand-border/40 pb-3 flex items-center gap-3">
                <FiLock className="w-5 h-5 text-brand-pink shrink-0" />
                Governing Law
              </h2>
              <p>
                This Privacy Policy is governed by the laws of India, and any disputes arising from it will be subject to the exclusive jurisdiction of the courts of India.
              </p>
            </section>

            {/* Contact */}
            <section className="space-y-4">
              <h2 className="font-serif text-xl sm:text-2xl font-bold text-brand-navy border-b border-brand-border/40 pb-3 flex items-center gap-3">
                <FiPhoneCall className="w-5 h-5 text-brand-pink shrink-0" />
                Contact Us
              </h2>
              <p>
                Don&apos;t hesitate to contact us if you have any questions or concerns regarding this policy.
              </p>
              <div className="bg-brand-bg/50 border border-brand-border/40 rounded-2xl p-6 space-y-3">
                <p className="flex items-center gap-2">
                  <span className="font-semibold text-brand-navy w-24">Via Email:</span>
                  <a href="mailto:support@nielacare.com" className="text-brand-pink hover:underline font-semibold">
                    support@nielacare.com
                  </a>
                </p>
                <p className="flex items-center gap-2">
                  <span className="font-semibold text-brand-navy w-24">Via Phone:</span>
                  <a href="tel:+918079037352" className="text-brand-pink hover:underline font-semibold">
                    +91 80790 37352
                  </a>
                </p>
              </div>
            </section>

          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
