import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Privacy Policy | Niela",
};

export default function PrivacyPage() {
  return (
    <>
      <Header />
      <main className="bg-emerald-50 min-h-screen">
            <div className="max-w-3xl mx-auto px-6 py-16 sm:py-20">
      <h1 className="text-4xl sm:text-5xl font-serif text-slate-800 text-center mb-12">
        Privacy Policy
      </h1>

      <div className="space-y-6 text-slate-700 leading-relaxed">
        <p>
          Niela (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;) is
          committed to protecting your privacy. This Privacy Policy
          explains how your personal information is collected, used, and
          disclosed when you use our website and services.
        </p>
        <p>
          This Privacy Policy applies to our website and its associated
          subdomains (collectively, our &quot;Service&quot;). By accessing
          or using our Service, you signify that you have read,
          understood, and agree to our collection, storage, use, and
          disclosure of your personal information as described in this
          Privacy Policy and our Terms of Use.
        </p>

        <h2 className="text-2xl font-semibold text-slate-800 pt-4">
          Definitions and Key Terms
        </h2>
        <p>
          To help explain things as clearly as possible, whenever these
          terms are used in this Privacy Policy, they carry the following
          meaning:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>
            <strong>Cookie:</strong> a small amount of data generated by a
            website and saved by your web browser, used to identify your
            browser, provide analytics, or remember your preferences and
            login information.
          </li>
          <li>
            <strong>Company:</strong> when this policy refers to
            &quot;Company,&quot; &quot;we,&quot; &quot;us,&quot; or
            &quot;our,&quot; it means <strong>Poiya Healthcare India
            Private Limited</strong>, the entity responsible for your
            information under this Privacy Policy.
          </li>
          <li>
            <strong>Country:</strong> where Niela and its owners are
            based, in this case, India.
          </li>
          <li>
            <strong>Device:</strong> any internet-connected device — such
            as a phone, tablet, or computer — used to visit Niela and use
            our services.
          </li>
          <li>
            <strong>IP Address:</strong> a number assigned to every
            internet-connected device, often used to estimate the general
            location from which a device is connecting.
          </li>
          <li>
            <strong>Personal Data:</strong> any information that directly
            or indirectly allows for the identification of a natural
            person.
          </li>
          <li>
            <strong>Service:</strong> refers to the service provided by
            Niela as described on this website.
          </li>
          <li>
            <strong>Third-Party Service:</strong> refers to advertisers,
            promotional and marketing partners, and others who provide
            content or services we think may interest you.
          </li>
          <li>
            <strong>Website:</strong> Niela&apos;s site, accessible via{" "}
            <strong><a href = "www.nielacare.com">nielacare.com</a></strong>.
          </li>
          <li>
            <strong>You:</strong> a person or entity that visits or
            registers with Niela to use our Services.
          </li>
        </ul>

        <h2 className="text-2xl font-semibold text-slate-800 pt-4">
          What Information Do We Collect?
        </h2>
        <p>
          We collect information from you when you visit our website,
          register on our site, place an order, subscribe to our
          newsletter, or fill out a form. This may include:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Name / Username</li>
          <li>Phone Numbers</li>
          <li>Email Addresses</li>
          <li>Mailing Addresses</li>
        </ul>

        <h2 className="text-2xl font-semibold text-slate-800 pt-4">
          How Do We Use The Information We Collect?
        </h2>
        <p>Any information we collect from you may be used to:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Personalize your experience on our website</li>
          <li>Improve our website based on your feedback</li>
          <li>Improve customer service and support</li>
          <li>Process transactions</li>
          <li>Administer a contest, promotion, survey, or other feature</li>
          <li>Send periodic emails and order updates</li>
        </ul>

        <h2 className="text-2xl font-semibold text-slate-800 pt-4">
          Do We Share Information With Third Parties?
        </h2>
        <p>
          We may share the personal and non-personal information we
          collect with trusted third-party service providers who help us
          operate our business — such as website hosting, database
          management, email delivery, payment processing (including our
          gateway partner Razorpay), and order fulfillment. These parties
          are only given the information they need to perform their
          services for us and are required to keep it confidential.
        </p>
        <p>
          We may also disclose personal information to government or law
          enforcement authorities where we believe in good faith that
          disclosure is necessary to comply with a legal obligation,
          protect our rights, or ensure the safety of our users.
        </p>

        <h2 className="text-2xl font-semibold text-slate-800 pt-4">
          How Do We Use Your Email Address?
        </h2>
        <p>
          By submitting your email address on this website, you agree to
          receive emails from us regarding your orders, offers, and
          updates. You can unsubscribe at any time using the link included
          in any email we send. We do not send unsolicited commercial
          emails.
        </p>

        <h2 className="text-2xl font-semibold text-slate-800 pt-4">
          How Long Do We Keep Your Information?
        </h2>
        <p>
          We retain your information only for as long as necessary to
          provide our Service and fulfill the purposes described in this
          policy, or as required to meet our legal obligations. When it is
          no longer needed, we remove it from our systems or
          de-personalize it.
        </p>

        <h2 className="text-2xl font-semibold text-slate-800 pt-4">
          How Do We Protect Your Information?
        </h2>
        <p>
          We implement a variety of security measures to protect your
          personal information. All sensitive or payment information is
          transmitted via Secure Socket Layer (SSL) technology and
          processed through our secure payment gateway partner. Your
          payment details are never stored on our servers after a
          transaction is complete. While we take reasonable steps to
          protect your information, no method of transmission or storage
          is 100% secure, and we cannot guarantee absolute security.
        </p>

        <h2 className="text-2xl font-semibold text-slate-800 pt-4">
          Can I Update or Correct My Information?
        </h2>
        <p>
          You can contact us at any time to update or correct your
          personal information, change your communication preferences, or
          request deletion of your account and associated data. We may
          take reasonable steps, such as verifying your identity, before
          making these changes.
        </p>

        <h2 className="text-2xl font-semibold text-slate-800 pt-4">
          Cookies
        </h2>
        <p>
          Niela uses cookies to identify the areas of our website you have
          visited and to enhance site performance and functionality.
          Cookies are non-essential, but disabling them may limit certain
          features, such as staying logged in between visits. You can
          disable cookies through your browser settings at any time.
        </p>

        <h2 className="text-2xl font-semibold text-slate-800 pt-4">
          Advertising and Remarketing
        </h2>
        <p>
          Our website may use remarketing and interest-based advertising
          services, such as the Facebook Pixel, to show you more relevant
          ads based on your browsing activity on our site. We are not
          responsible for the content or privacy practices of third-party
          advertisers or websites linked from our Service.
        </p>

        <h2 className="text-2xl font-semibold text-slate-800 pt-4">
          Children&apos;s Privacy
        </h2>
        <p>
          Our Service is not directed at children, and we do not
          knowingly collect personal information from children under the
          age of 13. If you are a parent or guardian and believe your
          child has provided us with personal data without your consent,
          please contact us so we can remove it.
        </p>

        <h2 className="text-2xl font-semibold text-slate-800 pt-4">
          Changes To This Privacy Policy
        </h2>
        <p>
          We may update this Privacy Policy from time to time to reflect
          changes to our Service or legal requirements. We will notify you
          of significant changes through our website. Continued use of
          our Service after changes take effect means you accept the
          updated policy.
        </p>

        <h2 className="text-2xl font-semibold text-slate-800 pt-4">
          Governing Law
        </h2>
        <p>
          This Privacy Policy is governed by the laws of India, and any
          disputes arising from it will be subject to the exclusive
          jurisdiction of the courts of India.
        </p>

        <h2 className="text-2xl font-semibold text-slate-800 pt-4">
          Contact Us
        </h2>
        <p>Don&apos;t hesitate to contact us if you have any questions.</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>
            Via Email:{" "}
            <a
              href="mailto:support@nielacare.com"
              className="text-brand-pink hover:underline"></a>
            <a>
              support@nielacare.com
            </a>
          </li>
          <li>
            Via Phone:{" "}
            <a
              href="tel:+918079037352"
              className="text-brand-pink hover:underline"></a>
           <a>
              +91 80790 37352
            </a>
          </li>
        </ul>
      </div>
    </div>
      </main>
      <Footer />
    </>
  );
}

